# Generated by Django 5.2.4 on 2025-08-11 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_alter_historyset_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='historyset',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='historyset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['history_set', 'created_at'], name='histories_h_history_31e2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='historyset',
            index=models.Index(fields=['updated_at'], name='histories_h_updated_223522_idx'),
        ),
    ]
