# Generated by Django 5.2.4 on 2025-08-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0004_alter_history_options_alter_historyset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['created_at']},
        ),
    ]
