openapi: 3.0.4
info:
  title: Subtitles API
  version: 1.0.0
  description: REST API for the Subtitles application

servers:
  - url: http://127.0.0.1:8000
    description: Local
  - url: https://subtitles-backend-production.up.railway.app
    description: Production

paths:
  /v1/register/:
    $ref: "./paths/register.yaml"
  /v1/token/:
    $ref: "./paths/token.yaml"
  /v1/token/refresh/:
    $ref: "./paths/token-refresh.yaml"
  /v1/history-set/:
    $ref: "./paths/history-set.yaml"
  /v1/history-set/{history_set_id}/:
    $ref: "./paths/history-set-detail.yaml"
  /v1/history-set/{history_set_id}/history/:
    $ref: "./paths/history-set-history.yaml"
  /health/live/:
    $ref: "./paths/health-live.yaml"
  /health/ready/:
    $ref: "./paths/health-ready.yaml"

components:
  schemas:
    RegisterRequest:
      $ref: "./components/schemas/request.yaml#/RegisterRequest"

    LoginRequest:
      $ref: "./components/schemas/request.yaml#/LoginRequest"
    LoginResponse:
      $ref: "./components/schemas/response.yaml#/LoginResponse"

    TokenRefreshRequest:
      $ref: "./components/schemas/request.yaml#/TokenRefreshRequest"
    TokenRefreshResponse:
      $ref: "./components/schemas/response.yaml#/TokenRefreshResponse"

    ListHistorySetRequest:
      $ref: "./components/schemas/request.yaml#/ListHistorySetRequest"
    ListHistorySetResponse:
      $ref: "./components/schemas/response.yaml#/ListHistorySetResponse"

    RetrieveHistorySetRequest:
      $ref: "./components/schemas/request.yaml#/RetrieveHistorySetRequest"
    RetrieveHistorySetResponse:
      $ref: "./components/schemas/response.yaml#/RetrieveHistorySetResponse"

    CreateHistorySetRequest:
      $ref: "./components/schemas/request.yaml#/CreateHistorySetRequest"
    CreateHistorySetResponse:
      $ref: "./components/schemas/response.yaml#/CreateHistorySetResponse"

    UpdateHistorySetRequest:
      $ref: "./components/schemas/request.yaml#/UpdateHistorySetRequest"
    UpdateHistorySetResponse:
      $ref: "./components/schemas/response.yaml#/UpdateHistorySetResponse"

    DeleteHistorySetRequest:
      $ref: "./components/schemas/request.yaml#/DeleteHistorySetRequest"
    DeleteHistorySetResponse:
      $ref: "./components/schemas/response.yaml#/DeleteHistorySetResponse"

    ListHistoryRequest:
      $ref: "./components/schemas/request.yaml#/ListHistoryRequest"
    ListHistoryResponse:
      $ref: "./components/schemas/response.yaml#/ListHistoryResponse"

    HistorySetResults:
      $ref: "./components/schemas/response.yaml#/HistorySetResults"
    HistoryResults:
      $ref: "./components/schemas/response.yaml#/HistoryResults"

    CreateHistoryRequest:
      $ref: "./components/schemas/request.yaml#/CreateHistoryRequest"
    CreateHistoryResponse:
      $ref: "./components/schemas/response.yaml#/CreateHistoryResponse"

    ErrorResponse:
      $ref: "./components/schemas/response.yaml#/ErrorResponse"
    AuthenticationErrorResponse:
      $ref: "./components/schemas/response.yaml#/AuthenticationErrorResponse"
    ServerErrorResponse:
      $ref: "./components/schemas/response.yaml#/ServerErrorResponse"
    ServiceUnavailableErrorResponse:
      $ref: "./components/schemas/response.yaml#/ServiceUnavailableErrorResponse"

    PaginatedResponseBase:
      $ref: "./components/schemas/response.yaml#/PaginatedResponseBase"
    HealthCheckResponse:
      $ref: "./components/schemas/response.yaml#/HealthCheckResponse"

  responses:
    NoContentResponse:
      $ref: "./components/responses.yaml#/NoContentResponse"
    ForbiddenResponse:
      $ref: "./components/responses.yaml#/ForbiddenResponse"
    UnauthorizedResponse:
      $ref: "./components/responses.yaml#/UnauthorizedResponse"
    BadRequestResponse:
      $ref: "./components/responses.yaml#/BadRequestResponse"
    InternalServerErrorResponse:
      $ref: "./components/responses.yaml#/InternalServerErrorResponse"
    ServiceUnavailableErrorResponse:
      $ref: "./components/responses.yaml#/ServiceUnavailableErrorResponse"

  parameters:
    LimitParam:
      $ref: "./components/parameters.yaml#/LimitParam"
    OffsetParam:
      $ref: "./components/parameters.yaml#/OffsetParam"

  examples:
    RegisterRequestExample:
      $ref: "./components/examples.yaml#/RegisterRequestExample"
    LoginRequestExample:
      $ref: "./components/examples.yaml#/LoginRequestExample"
    LoginResponseExample:
      $ref: "./components/examples.yaml#/LoginResponseExample"
